services:
  web:
    build: ../web-client
    ports:
      - 80:3000
    depends_on:
      - backend

  backend:
    build:
      context: ../python-service
      network: host
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb:
