services:
  web:
    build: 
      context: ../web-client
    ports:
      - 80:3000
  backend-service:
    container_name: bratiki-backend
    build: ../python-service
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    container_name: bratiki-mongodb
    image: mongo:8.0.1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb:
